<a href="https://colab.research.google.com/github/yashkapoor279/CS50-PYTHON-COURSE/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY ARRAYS**

**CREATING NUMPY** **ARRAYS**

In [ ]:
#CREATING FIRST NUMPY PROGRAM
import numpy as np
# a = np.array([3,4,5])
a = np.array([[3,4,5],[6,7,8],[9,10,11]]) #2D array
print(a)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c) # elements contained in a list #can be list of list


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#dtype
import numpy as np
# np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=complex)
# np.array([1,2,3],dtype=bool)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#np.arange
#suppose we need to print numbers from 1-10 as array
np.arange(1,11) #np.arange(included start,excluded end)
np.arange(1,11,2) #np.arange(included start,excluded end,step)

array([1, 3, 5, 7, 9])

In [ ]:
#with reshape
np.arange(1,13).reshape(4,3)  #(rows,columns)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**INITIALISATION TECHNIQUES**

In [ ]:
#np.ones and np.zeroes
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.zeroes -. used to initialise
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.61392812, 0.62334758, 0.27782342, 0.65474086],
       [0.55404625, 0.91179639, 0.36311284, 0.85856721],
       [0.81591425, 0.05305999, 0.47195563, 0.45361165]])

In [ ]:
#np.linspace(linear spaced)
np.linspace(-5,5,7) #(lower range,upper range , no. of elements you want)

array([-5.        , -3.33333333, -1.66666667,  0.        ,  1.66666667,
        3.33333333,  5.        ])

In [ ]:
#np.identity
np.identity(6,dtype=int) #produce an identity matrix of order 6

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

**ARRAY ATTRIBUTES**

In [ ]:
a1=np.arange(10 , dtype=np.int32)
a2=np.arange(10).reshape(2,5)
a3=np.arange(8).reshape(2,2,2)

a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(10).reshape(2,5)
a3=np.arange(8).reshape(2,2,2)

a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a1=np.arange(10)
a2=np.arange(10).reshape(2,5)
a3=np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#ndim  -> Kitna dimension hai 1-D,2-D,3-D
a1.ndim
a2.ndim


2

In [ ]:
#shape
import numpy as np
a2.shape  #o/p-> (2,5)
a3.shape  #o/p-> (2,2,2)


(2, 2, 2)

In [ ]:
#size -> tells no. of items
# a3.size
print(a2.size)
a2


10


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#itemsize -> hr item memory mei kitna size occupy kr rha hai(ex : int 8 leta hai )
a3.itemsize

8

In [ ]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int64
int64


**CHANGING DATATYPES**

In [ ]:
#astype
a3.astype(np.int32)  #reducing memory size from int 64 to int 32

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**ARRAY OPERATIONS**

In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#scalar operation
a1*2  #every element multiplied with 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
#relational > < == <= >=
a2>17  #True if condition satisfies

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operations
a1 + a2  #since shape of both matrix is same so the corresponding element gets operated

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

**ARRAY FUNCTIONS**

In [ ]:
import numpy as np
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1 #random numbers generate din the range of 1 to 100

array([[77., 22., 46.],
       [85., 67., 74.],
       [40., 71., 87.]])

In [ ]:
#max/min/sum/prod
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

np.float64(8113986456945600.0)

In [ ]:
#Find the maximum element in each row
#0->column 1->row
np.max(a1,axis=1) #rowise


array([77., 85., 87.])

In [ ]:
#mean/median/std/var
np.mean(a1,axis=0) #columnwise

array([67.33333333, 53.33333333, 69.        ])

In [ ]:
#median
np.median(a1)  #22 40 46 67 71(median) 74 77 85 87

np.float64(71.0)

In [ ]:
#std
np.std(a1)  #batata hai ki data ke numbers average (mean) se kitne zyada ya kam door hain.

np.float64(20.964402515681343)

In [ ]:
np.var(a1 ,axis=1)

array([506.88888889,  54.88888889, 380.66666667])

In [ ]:
#trigonometric
np.sin(a1)

array([[ 0.99952016, -0.00885131,  0.90178835],
       [-0.17607562, -0.85551998, -0.98514626],
       [ 0.74511316,  0.95105465, -0.82181784]])

In [ ]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)


np.dot(a2,a3)  #matrix multipliation


#applicable only when the column of first is equal to row of second

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exp
np.log(a1)

array([[4.34380542, 3.09104245, 3.8286414 ],
       [4.44265126, 4.20469262, 4.30406509],
       [3.68887945, 4.26267988, 4.46590812]])

In [ ]:
np.exp(a1)

array([[2.75851345e+33, 3.58491285e+09, 9.49611942e+19],
       [8.22301271e+36, 1.25236317e+29, 1.37338298e+32],
       [2.35385267e+17, 6.83767123e+30, 6.07603023e+37]])

In [ ]:
#round/floor/ceil
np.round(np.random.random((2,3))*100) #roundoff to closest integers

array([[81., 87., 34.],
       [28., 19., 45.]])

In [ ]:
#floor
#6.9-> 6  8.999->7
np.floor(a1)
#ceil
#7.1->8
np.ceil(a1)

array([[77., 22., 46.],
       [85., 67., 74.],
       [40., 71., 87.]])

**INDEXING AND SLICING**

In [4]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [5]:
import numpy as np
a1[-1] #fetching last item #elemnts can be accessed in 1D through indexing

np.int64(9)

In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
#access 6 from 2d array
a2[1,2]  #a2[row , column]

np.int64(6)

In [10]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
#accessing from 3D(array of 2d array)
a3[1,0,1] #a3[konsa 2D array , konsi row ,konsi column]

np.int64(5)

In [12]:
#slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#accessing 2,3,4 from a1
a1[2:5] #a1[inclusive start:exclusive end:step size(optional)]


array([], dtype=int64)

In [15]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
#accessing first row
a2[0,:]

array([0, 1, 2, 3])

In [18]:
#accessing 3rd column
a2[:,2]

array([ 2,  6, 10])

In [19]:
a2[1:,1:3] #accessing a particular block

array([[ 5,  6],
       [ 9, 10]])

In [20]:
a2[::2,::3]   #::2-> row with jump of two,::3->column with jump of three

array([[ 0,  3],
       [ 8, 11]])

In [21]:
a2[::2,1::2] #->rows = 0 onwards with jump pf 2....cols=one onwards with jump of two

array([[ 1,  3],
       [ 9, 11]])

In [22]:
a2[::2,2::]

array([[ 2,  3],
       [10, 11]])

In [23]:
#accessing 4 and 7
a2[1,0::3]

array([4, 7])

In [27]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [31]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
a3[1] #accessing arrays at index 1

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [33]:
a3[::2] #alternate

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
a3[0,1,:] #->1st 2D array ka second row aur all columns

array([3, 4, 5])

In [35]:
a3[1,:,1]

array([10, 13, 16])

In [36]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [38]:
a3[::2,0,::2] #accessing elemnts from two different 2D arrays

array([[ 0,  2],
       [18, 20]])

**ITERATING**

In [42]:
a1

for i in a1 :
  print(i)

0
1
2
3
4
5
6
7
8
9


In [44]:
a2

for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [46]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [47]:
for i in np.nditer(a3):  #printing one one element from a multi dim array
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


**RESHAPING**

In [48]:
#TRANSPOSE
np.transpose(a2) or#a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [50]:
#ravel -> converts multidimension array to 1D
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

**STACKING**

In [52]:
#stacking or adding two or more numpy arrays horizontally or vertically
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
#horizontal stack
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [55]:
#vertical stack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
#splitting
#hsplit
a4
np.hsplit(a4,4)  #hplit(konsa matrix , kitne parts mei kaatna)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [62]:
#vsplit
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]